// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogpageDocumentDataSlicesSlice = BlogSlice | HerosectionSlice;

/**
 * Content for blogpage documents
 */
interface BlogpageDocumentData {
  /**
   * Slice Zone field in *blogpage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpageDocumentDataSlicesSlice> /**
   * Meta Title field in *blogpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blogpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blogpage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blogpage document from Prismic
 *
 * - **API ID**: `blogpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpageDocumentData>,
    "blogpage",
    Lang
  >;

type BlogsDocumentDataSlicesSlice = HerosectionSlice;

/**
 * Content for Blogs documents
 */
interface BlogsDocumentData {
  /**
   * Slice Zone field in *Blogs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogsDocumentDataSlicesSlice>;
}

/**
 * Blogs document from Prismic
 *
 * - **API ID**: `blogs`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogsDocumentData>, "blogs", Lang>;

/**
 * Item in *Error → btn*
 */
export interface ErrorDocumentDataBtnItem {
  /**
   * title field in *Error → btn*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: error.btn[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * black_bg field in *Error → btn*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: error.btn[].black_bg
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  black_bg: prismic.BooleanField;

  /**
   * url field in *Error → btn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: error.btn[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

type ErrorDocumentDataSlicesSlice = HerosectionSlice;

/**
 * Content for Error documents
 */
interface ErrorDocumentData {
  /**
   * error img field in *Error*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: error.error_img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  error_img: prismic.ImageField<never>;

  /**
   * heading field in *Error*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: error.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * desc field in *Error*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: error.desc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  desc: prismic.KeyTextField;

  /**
   * btn field in *Error*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: error.btn[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  btn: prismic.GroupField<Simplify<ErrorDocumentDataBtnItem>>;

  /**
   * Slice Zone field in *Error*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: error.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ErrorDocumentDataSlicesSlice>;
}

/**
 * Error document from Prismic
 *
 * - **API ID**: `error`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ErrorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ErrorDocumentData>, "error", Lang>;

/**
 * Item in *Footer → btn*
 */
export interface FooterDocumentDataBtnItem {
  /**
   * title field in *Footer → btn*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.btn[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * black_bg field in *Footer → btn*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: footer.btn[].black_bg
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  black_bg: prismic.BooleanField;

  /**
   * url field in *Footer → btn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.btn[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

type FooterDocumentDataSlicesSlice = FooterListSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * cta img field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta_img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_img: prismic.ImageField<never>;

  /**
   * cta title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * btn field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.btn[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  btn: prismic.GroupField<Simplify<FooterDocumentDataBtnItem>>;

  /**
   * logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * logo title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo_title: prismic.KeyTextField;

  /**
   * footer description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_description: prismic.KeyTextField;

  /**
   * cta title color field in *Footer*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: footer.cta_title_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta_title_color: prismic.BooleanField;

  /**
   * logo url field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_url: prismic.LinkField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Navbar → navlist*
 */
export interface NavbarDocumentDataNavlistItem {
  /**
   * link title field in *Navbar → navlist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navlist[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * url field in *Navbar → navlist*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navlist[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Item in *Navbar → btn*
 */
export interface NavbarDocumentDataBtnItem {
  /**
   * title field in *Navbar → btn*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.btn[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * black bg field in *Navbar → btn*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navbar.btn[].black_bg
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  black_bg: prismic.BooleanField;

  /**
   * url field in *Navbar → btn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.btn[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * logo field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * logo title field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo_title: prismic.KeyTextField;

  /**
   * logo url field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_url: prismic.LinkField;

  /**
   * navlist field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navlist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navlist: prismic.GroupField<Simplify<NavbarDocumentDataNavlistItem>>;

  /**
   * tel icon field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.tel_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tel_icon: prismic.ImageField<never>;

  /**
   * tel field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.tel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tel: prismic.KeyTextField;

  /**
   * btn field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.btn[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  btn: prismic.GroupField<Simplify<NavbarDocumentDataBtnItem>>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactUsSlice
  | CredentialsSlice
  | TestimonialsSlice
  | ServicesSlice
  | ArticlesSlice
  | FooterListSlice
  | HerosectionSlice
  | AboutSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | BlogpageDocument
  | BlogsDocument
  | ErrorDocument
  | FooterDocument
  | NavbarDocument
  | PageDocument;

/**
 * Item in *About → Default → Primary → lists*
 */
export interface AboutSliceDefaultPrimaryListsItem {
  /**
   * list item field in *About → Default → Primary → lists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.lists[].list_item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  list_item: prismic.KeyTextField;
}

/**
 * Item in *About → Default → Primary → btn*
 */
export interface AboutSliceDefaultPrimaryBtnItem {
  /**
   * title field in *About → Default → Primary → btn*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.btn[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * black_bg field in *About → Default → Primary → btn*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: about.default.primary.btn[].black_bg
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  black_bg: prismic.BooleanField;

  /**
   * url field in *About → Default → Primary → btn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.btn[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * about img field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  about_img: prismic.ImageField<never>;

  /**
   * heading icon field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.heading_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heading_icon: prismic.ImageField<never>;

  /**
   * heading field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * lists field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.lists[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  lists: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryListsItem>>;

  /**
   * btn field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.btn[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  btn: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryBtnItem>>;

  /**
   * direction field in *About → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Slice Direction
   * - **Default Value**: Left
   * - **API ID Path**: about.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<"Left" | "Right", "filled">;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Articles → Default → Primary → Article Card*
 */
export interface ArticlesSliceDefaultPrimaryArticleCardItem {
  /**
   * btn title field in *Articles → Default → Primary → Article Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.article_card[].btn_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_title: prismic.KeyTextField;

  /**
   * btn url field in *Articles → Default → Primary → Article Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.article_card[].btn_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_url: prismic.LinkField;

  /**
   * cal img field in *Articles → Default → Primary → Article Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.article_card[].cal_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cal_img: prismic.ImageField<never>;

  /**
   * date field in *Articles → Default → Primary → Article Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.article_card[].date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * bg img field in *Articles → Default → Primary → Article Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.article_card[].bg_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_img: prismic.ImageField<never>;

  /**
   * description field in *Articles → Default → Primary → Article Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.article_card[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Articles → Default → Primary*
 */
export interface ArticlesSliceDefaultPrimary {
  /**
   * Heading field in *Articles → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Article Card field in *Articles → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.default.primary.article_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  article_card: prismic.GroupField<
    Simplify<ArticlesSliceDefaultPrimaryArticleCardItem>
  >;
}

/**
 * Default variation for Articles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticlesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Articles*
 */
type ArticlesSliceVariation = ArticlesSliceDefault;

/**
 * Articles Shared Slice
 *
 * - **API ID**: `articles`
 * - **Description**: Articles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesSlice = prismic.SharedSlice<
  "articles",
  ArticlesSliceVariation
>;

/**
 * Item in *Blog → Default → Primary → card content*
 */
export interface BlogSliceDefaultPrimaryCardContentItem {
  /**
   * show img field in *Blog → Default → Primary → card content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.card_content[].show_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  show_img: prismic.ImageField<never>;

  /**
   * heading field in *Blog → Default → Primary → card content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.card_content[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * showdesc field in *Blog → Default → Primary → card content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.card_content[].showdesc
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  showdesc: prismic.KeyTextField;
}

/**
 * Item in *Blog → Default → Primary → content*
 */
export interface BlogSliceDefaultPrimaryContentItem {
  /**
   * content field in *Blog → Default → Primary → content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.content[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Blog → Default → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * card content field in *Blog → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.card_content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card_content: prismic.GroupField<
    Simplify<BlogSliceDefaultPrimaryCardContentItem>
  >;

  /**
   * content field in *Blog → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<Simplify<BlogSliceDefaultPrimaryContentItem>>;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Item in *ContactUs → Default → Primary → heading*
 */
export interface ContactUsSliceDefaultPrimaryHeadingItem {
  /**
   * first field in *ContactUs → Default → Primary → heading*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.heading[].first
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first: prismic.KeyTextField;

  /**
   * second field in *ContactUs → Default → Primary → heading*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.heading[].second
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second: prismic.KeyTextField;

  /**
   * reverse field in *ContactUs → Default → Primary → heading*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: contact_us.default.primary.heading[].reverse
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * Item in *ContactUs → Default → Primary → btn*
 */
export interface ContactUsSliceDefaultPrimaryBtnItem {
  /**
   * title field in *ContactUs → Default → Primary → btn*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.btn[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * black_bg field in *ContactUs → Default → Primary → btn*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: contact_us.default.primary.btn[].black_bg
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  black_bg: prismic.BooleanField;

  /**
   * url field in *ContactUs → Default → Primary → btn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.btn[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Primary content in *ContactUs → Default → Primary*
 */
export interface ContactUsSliceDefaultPrimary {
  /**
   * heading field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.heading[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  heading: prismic.GroupField<
    Simplify<ContactUsSliceDefaultPrimaryHeadingItem>
  >;

  /**
   * plcholder_first field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.plcholder_first
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plcholder_first: prismic.KeyTextField;

  /**
   * plcholder_second field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.plcholder_second
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plcholder_second: prismic.KeyTextField;

  /**
   * plcholder_email field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.plcholder_email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plcholder_email: prismic.KeyTextField;

  /**
   * plcholder_phone field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.plcholder_phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plcholder_phone: prismic.KeyTextField;

  /**
   * plcholder_msg field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.plcholder_msg
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plcholder_msg: prismic.KeyTextField;

  /**
   * btn field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.btn[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  btn: prismic.GroupField<Simplify<ContactUsSliceDefaultPrimaryBtnItem>>;
}

/**
 * Default variation for ContactUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUs*
 */
type ContactUsSliceVariation = ContactUsSliceDefault;

/**
 * ContactUs Shared Slice
 *
 * - **API ID**: `contact_us`
 * - **Description**: ContactUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSlice = prismic.SharedSlice<
  "contact_us",
  ContactUsSliceVariation
>;

/**
 * Item in *Credentials → Default → Primary → creds*
 */
export interface CredentialsSliceDefaultPrimaryCredsItem {
  /**
   * heading field in *Credentials → Default → Primary → creds*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credentials.default.primary.creds[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *Credentials → Default → Primary → creds*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credentials.default.primary.creds[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Credentials → Default → Primary*
 */
export interface CredentialsSliceDefaultPrimary {
  /**
   * creds field in *Credentials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credentials.default.primary.creds[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  creds: prismic.GroupField<Simplify<CredentialsSliceDefaultPrimaryCredsItem>>;
}

/**
 * Default variation for Credentials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CredentialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CredentialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Credentials*
 */
type CredentialsSliceVariation = CredentialsSliceDefault;

/**
 * Credentials Shared Slice
 *
 * - **API ID**: `credentials`
 * - **Description**: Credentials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CredentialsSlice = prismic.SharedSlice<
  "credentials",
  CredentialsSliceVariation
>;

/**
 * Item in *FooterList → Default → Primary → footer list*
 */
export interface FooterListSliceDefaultPrimaryFooterListItem {
  /**
   * items field in *FooterList → Default → Primary → footer list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_list.default.primary.footer_list[].items
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  items: prismic.KeyTextField;

  /**
   * url field in *FooterList → Default → Primary → footer list*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_list.default.primary.footer_list[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Primary content in *FooterList → Default → Primary*
 */
export interface FooterListSliceDefaultPrimary {
  /**
   * label field in *FooterList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_list.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * footer list field in *FooterList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_list.default.primary.footer_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_list: prismic.GroupField<
    Simplify<FooterListSliceDefaultPrimaryFooterListItem>
  >;
}

/**
 * Default variation for FooterList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterList*
 */
type FooterListSliceVariation = FooterListSliceDefault;

/**
 * FooterList Shared Slice
 *
 * - **API ID**: `footer_list`
 * - **Description**: FooterList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterListSlice = prismic.SharedSlice<
  "footer_list",
  FooterListSliceVariation
>;

/**
 * Item in *Herosection → Default → Primary → heading*
 */
export interface HerosectionSliceDefaultPrimaryHeadingItem {
  /**
   * first field in *Herosection → Default → Primary → heading*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.heading[].first
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first: prismic.KeyTextField;

  /**
   * second field in *Herosection → Default → Primary → heading*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.heading[].second
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second: prismic.KeyTextField;

  /**
   * reverse field in *Herosection → Default → Primary → heading*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: herosection.default.primary.heading[].reverse
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * Item in *Herosection → Default → Primary → btn*
 */
export interface HerosectionSliceDefaultPrimaryBtnItem {
  /**
   * title field in *Herosection → Default → Primary → btn*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.btn[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * black_bg field in *Herosection → Default → Primary → btn*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: herosection.default.primary.btn[].black_bg
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  black_bg: prismic.BooleanField;

  /**
   * url field in *Herosection → Default → Primary → btn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.btn[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Primary content in *Herosection → Default → Primary*
 */
export interface HerosectionSliceDefaultPrimary {
  /**
   * bg img field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.bg_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_img: prismic.ImageField<never>;

  /**
   * heading field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.heading[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  heading: prismic.GroupField<
    Simplify<HerosectionSliceDefaultPrimaryHeadingItem>
  >;

  /**
   * description field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * btn field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: herosection.default.primary.btn[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  btn: prismic.GroupField<Simplify<HerosectionSliceDefaultPrimaryBtnItem>>;
}

/**
 * Default variation for Herosection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HerosectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HerosectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Herosection*
 */
type HerosectionSliceVariation = HerosectionSliceDefault;

/**
 * Herosection Shared Slice
 *
 * - **API ID**: `herosection`
 * - **Description**: Herosection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HerosectionSlice = prismic.SharedSlice<
  "herosection",
  HerosectionSliceVariation
>;

/**
 * Item in *Services → Default → Primary → cards*
 */
export interface ServicesSliceDefaultPrimaryCardsItem {
  /**
   * card img field in *Services → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].card_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_img: prismic.ImageField<never>;

  /**
   * card heading field in *Services → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_heading: prismic.KeyTextField;

  /**
   * card description field in *Services → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_description: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Heading field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * cards field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<ServicesSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → testimonal cards*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonalCardItem {
  /**
   * icon field in *Testimonials → Default → Primary → testimonal cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonal_card[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * description field in *Testimonials → Default → Primary → testimonal cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonal_card[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * user img field in *Testimonials → Default → Primary → testimonal cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonal_card[].user_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  user_img: prismic.ImageField<never>;

  /**
   * user name field in *Testimonials → Default → Primary → testimonal cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonal_card[].user_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  user_name: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * testimonal cards field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonal_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonal_card: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonalCardItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogpageDocument,
      BlogpageDocumentData,
      BlogpageDocumentDataSlicesSlice,
      BlogsDocument,
      BlogsDocumentData,
      BlogsDocumentDataSlicesSlice,
      ErrorDocument,
      ErrorDocumentData,
      ErrorDocumentDataBtnItem,
      ErrorDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataBtnItem,
      FooterDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavlistItem,
      NavbarDocumentDataBtnItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryListsItem,
      AboutSliceDefaultPrimaryBtnItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      ArticlesSlice,
      ArticlesSliceDefaultPrimaryArticleCardItem,
      ArticlesSliceDefaultPrimary,
      ArticlesSliceVariation,
      ArticlesSliceDefault,
      BlogSlice,
      BlogSliceDefaultPrimaryCardContentItem,
      BlogSliceDefaultPrimaryContentItem,
      BlogSliceDefaultPrimary,
      BlogSliceVariation,
      BlogSliceDefault,
      ContactUsSlice,
      ContactUsSliceDefaultPrimaryHeadingItem,
      ContactUsSliceDefaultPrimaryBtnItem,
      ContactUsSliceDefaultPrimary,
      ContactUsSliceVariation,
      ContactUsSliceDefault,
      CredentialsSlice,
      CredentialsSliceDefaultPrimaryCredsItem,
      CredentialsSliceDefaultPrimary,
      CredentialsSliceVariation,
      CredentialsSliceDefault,
      FooterListSlice,
      FooterListSliceDefaultPrimaryFooterListItem,
      FooterListSliceDefaultPrimary,
      FooterListSliceVariation,
      FooterListSliceDefault,
      HerosectionSlice,
      HerosectionSliceDefaultPrimaryHeadingItem,
      HerosectionSliceDefaultPrimaryBtnItem,
      HerosectionSliceDefaultPrimary,
      HerosectionSliceVariation,
      HerosectionSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryCardsItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonalCardItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
