// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  articles: dynamic(() => import("./Articles")),
  blog: dynamic(() => import("./Blog")),
  contact_us: dynamic(() => import("./ContactUs")),
  credentials: dynamic(() => import("./Credentials")),
  footer_list: dynamic(() => import("./FooterList")),
  herosection: dynamic(() => import("./Herosection")),
  services: dynamic(() => import("./Services")),
  testimonials: dynamic(() => import("./Testimonials")),
};
